// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Descriptions: typeof import('./src/components/common-wrapper/Descriptions.vue')['default']
    Draggable: typeof import('./src/components/common-wrapper/Draggable.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    EleAutocomplete: typeof import('./src/components/visual-components/items/EleAutocomplete.vue')['default']
    EleCheckbox: typeof import('./src/components/visual-components/items/EleCheckbox.vue')['default']
    EleInput: typeof import('./src/components/visual-components/items/EleInput.vue')['default']
    EleRadio: typeof import('./src/components/visual-components/items/EleRadio.vue')['default']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    Form: typeof import('./src/components/common-wrapper/Form.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HoverDiv: typeof import('./src/components/HoverDiv.vue')['default']
    ItemsDraggableList: typeof import('./src/components/visual-components/ItemsDraggableList.vue')['default']
    ItemWrapper: typeof import('./src/components/visual-components/ItemWrapper.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    Postman: typeof import('./src/components/Postman.vue')['default']
    Splipanes: typeof import('./src/components/common-wrapper/Splipanes.vue')['default']
    Table: typeof import('./src/components/common-wrapper/Table.vue')['default']
    TinymceEditor: typeof import('./src/components/tinymce-editor/index.vue')['default']
  }
}

export { }
